<?php
/**
 * LaraCMS - CMS based on laravel
 *
 * @category  LaraCMS
 * @package   Laravel
 * @author    Wanglelecc <wanglelecc@gmail.com>
 * @date      2018/06/06 09:08:00
 * @copyright Copyright 2018 LaraCMS
 * @license   https://opensource.org/licenses/MIT
 * @github    https://github.com/wanglelecc/laracms
 * @link      https://www.laracms.cn
 * @version   Release 1.0
 */

namespace App\Http\Controllers\Administrator;

use DB;
use App\Models\Article;
use App\Http\Requests\Administrator\ArticleRequest;


/**
 * 后台文章管理控制器
 *
 * Class ArticlesController
 * @package Wanglelecc\Laracms\Http\Controllers\Administrator
 */
class ArticlesController extends Controller
{
    public function update(ArticleRequest $request, Article $article)
    {
        $this->authorize('update', $article);
        dd($request);
        $article->update($request->all());
        $article->syncCategory($request->category_id ?? []);

        return $this->redirect('articles.index')->with('success', '更新成功.');
        dd(1111); // TODO: Change the autogenerated stub
    }

}
